server:
  port: 8005

spring:
  application:
    name: cloudAlibaba-payment-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://masuo-sql.mysql.rds.aliyuncs.com:3306/cloudalibaba?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: masuo
    password: Mas+1006

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: payment8005

mybatis:
  # mapper文件所在位置
  mapper-locations: classpath:mapper/*.xml
  # 实体类所在文件
  type-aliases-package: com.marshio.cloudAlibaba.entities