server:
  port: 8010

spring:
  application:
    name: nacos-service
  cloud:
    nacos:
      discovery:
        # nacos 服务端地址
        server-addr: 127.0.0.1:8848
        # 隔离不同的服务实例
        namespace: public
