server:
  # 服务端口号
  port: 8001


spring:
  application:
    # 服务名称
    name: cloudAlibaba-payment-service
  datasource:
    # 数据源信息
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://masuo-sql.mysql.rds.aliyuncs.com:3306/cloudalibaba?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: masuo
    password: Mas+1006

#eureka:
#  client:
#    # 注册服务
#    register-with-eureka: true
#    # 发现服务
#    fetch-registry: true
#    # Eureka服务端地址
#    service-url:
#      # 这里必须要加 /eureka/ ，因为有过滤器做限制
#      defaultZone: http://localhost:7001/eureka/
#  instance:
#    instance-id: payment8001

mybatis:
  # mapper文件所在位置
  mapper-locations: classpath:mapper/*.xml
  # 实体类所在文件
  type-aliases-package: com.marshio.cloudAlibaba.entities

