server:
  # 服务端口号
  port: 8002



spring:
  application:
    # 服务名称
    name: cloudAlibaba-payment-service
  datasource:
    # 数据源信息
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://masuo-sql.mysql.rds.aliyuncs.com:3306/cloudalibaba?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: masuo
    password: Mas+1006
    druid:
      test-while-idle: false
#  cloud:
#    loadbalancer:
#      ribbon:
#        enabled: false

eureka:
  client:
    # 注册服务，将自己向注册中心注册时，
    register-with-eureka: true
    # 发现服务
    fetch-registry: true
    # Eureka服务端地址
    service-url:
      # 这里必须要加 /eureka 的后缀，不然会被过滤掉，导致找不到注册中心
      defaultZone: http://eurekaserve7002.com:7002/eureka,http://eurekaserve7003.com:7003/eureka

  instance:
    hostname: payment8002
    prefer-ip-address: true
    instance-id: payment8002

mybatis:
  # mapper文件所在位置
  mapper-locations: classpath:mapper/*.xml
  # 实体类所在文件
  type-aliases-package: com.marshio.cloudAlibaba.entities

