server:
  port: 8004

spring:
  application:
    name: cloudAlibaba-payment-service
  datasource:
    # 数据源信息
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://masuo-sql.mysql.rds.aliyuncs.com:3306/cloudalibaba?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: masuo
    password: Mas+1006
    druid:
      test-while-idle: false
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        # 向 consul 注册
        service-name: ${spring.application.name}